cask_args appdir: '/Applications'
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"

# packages
brew "git"
brew "telnet"
brew "coreutils"
brew "jq"
brew "fzf"
brew "yarn"
brew "zsh"
brew "bash"
brew "pandoc"
brew "tree"
brew "circleci"
brew "kubectl"
brew "rsync"

# pyenv and dependencies
brew "openssl"
brew "readline"
brew "sqlite3"
brew "xz"
brew "zlib"

# env managers
brew "pyenv"
brew "pyenv-virtualenv"
brew "goenv", args: ["HEAD"]
brew "rbenv"
brew "tfenv"

# browsers and apps
cask "iterm2"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "keepassxc"
cask "obsidian"
cask "rectangle"
cask "slack"
cask "tidal"
cask "zoom"

# IDEs and editors
cask "visual-studio-code"
