theme = "nordic"

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[editor.cursor-shape]
insert = "bar"

[editor]
line-number = "relative"
mouse = true
trim-trailing-whitespace = true
trim-final-newlines = true

[editor.file-picker]
hidden = false
